import type { Template } from '@/types';

/** Built-in templates. They are recreated on load, never written to IndexedDB. */
export const BUILT_IN_TEMPLATES: Template[] = [
  {
    id: 'builtin-weekly-reset',
    name: 'Weekly reset',
    description: 'A Sunday pass over the week ahead so Monday starts clean.',
    category: 'Routine',
    color: 'teal',
    icon: 'sparkles',
    builtIn: true,
    createdAt: 0,
    tasks: [
      { title: 'Clear the inbox to zero', priority: 'high', dueInDays: 0 },
      { title: 'Review last week', priority: 'medium', dueInDays: 0, children: [
        { title: 'What moved forward', priority: 'low' },
        { title: 'What stalled and why', priority: 'low' },
      ] },
      { title: 'Pick three outcomes for the week', priority: 'critical', dueInDays: 0 },
      { title: 'Block calendar time for deep work', priority: 'high', dueInDays: 1 },
      { title: 'Tidy the desk and downloads folder', priority: 'low', dueInDays: 1 },
    ],
  },
  {
    id: 'builtin-release',
    name: 'Software release',
    description: 'Cut, verify and ship a build without forgetting the boring steps.',
    category: 'Work',
    color: 'azure',
    icon: 'code',
    builtIn: true,
    createdAt: 0,
    tasks: [
      { title: 'Freeze the branch', priority: 'critical', dueInDays: 0 },
      { title: 'Run the full test suite', priority: 'critical', dueInDays: 0 },
      { title: 'Regression pass', priority: 'high', dueInDays: 1, children: [
        { title: 'Smoke test core flows', priority: 'high' },
        { title: 'Check mobile layout', priority: 'medium' },
        { title: 'Verify offline behaviour', priority: 'medium' },
      ] },
      { title: 'Update the changelog', priority: 'medium', dueInDays: 1 },
      { title: 'Tag the release', priority: 'high', dueInDays: 2 },
      { title: 'Deploy and watch logs for an hour', priority: 'critical', dueInDays: 2 },
      { title: 'Tell the team it shipped', priority: 'low', dueInDays: 2 },
    ],
  },
  {
    id: 'builtin-trip',
    name: 'Trip packing',
    description: 'Everything that ruins a trip if you leave it at home.',
    category: 'Personal',
    color: 'copper',
    icon: 'plane',
    builtIn: true,
    createdAt: 0,
    tasks: [
      { title: 'Documents', priority: 'critical', dueInDays: 1, children: [
        { title: 'ID and tickets', priority: 'critical' },
        { title: 'Offline copies on the phone', priority: 'high' },
      ] },
      { title: 'Chargers and adapters', priority: 'high', dueInDays: 1 },
      { title: 'Medication and first aid', priority: 'high', dueInDays: 1 },
      { title: 'Clothes for the forecast', priority: 'medium', dueInDays: 2 },
      { title: 'Download maps and playlists', priority: 'low', dueInDays: 2 },
      { title: 'Arrange keys, plants and post', priority: 'medium', dueInDays: 2 },
    ],
  },
  {
    id: 'builtin-morning',
    name: 'Morning routine',
    description: 'A short, repeatable start to the day.',
    category: 'Routine',
    color: 'moss',
    icon: 'heart',
    builtIn: true,
    createdAt: 0,
    tasks: [
      { title: 'Water and stretch', priority: 'medium', dueInDays: 0 },
      { title: 'Twenty minutes of movement', priority: 'high', dueInDays: 0 },
      { title: 'Plan the day in one line', priority: 'critical', dueInDays: 0 },
      { title: 'No screens for the first half hour', priority: 'low', dueInDays: 0 },
    ],
  },
  {
    id: 'builtin-interview',
    name: 'Interview prep',
    description: 'A week of preparation broken into sittings.',
    category: 'Career',
    color: 'violet',
    icon: 'book',
    builtIn: true,
    createdAt: 0,
    tasks: [
      { title: 'Re-read the job description and map it to experience', priority: 'high', dueInDays: 0 },
      { title: 'Write six stories in situation–action–result form', priority: 'critical', dueInDays: 2 },
      { title: 'Drill the core technical topics', priority: 'critical', dueInDays: 3, children: [
        { title: 'Fundamentals', priority: 'high' },
        { title: 'Hands-on exercise', priority: 'high' },
        { title: 'Two questions to ask them', priority: 'medium' },
      ] },
      { title: 'Mock interview out loud', priority: 'high', dueInDays: 4 },
      { title: 'Test the call setup, camera and light', priority: 'medium', dueInDays: 5 },
    ],
  },
];
